{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9c2fdac5",
   "metadata": {},
   "outputs": [],
   "source": [
    "import duckdb\n",
    "\n",
    "con = duckdb.connect('../database/test_duckdb.db')\n",
    "\n",
    "con.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9f4367dd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\python.exe\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "print(sys.executable)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "9dfaa266",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.3.2\n"
     ]
    }
   ],
   "source": [
    "import duckdb\n",
    "print(duckdb.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "ed4e6c10",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-07-18 11:20:12,715 INFO Starting DuckDB database creation script (Desktop test)\n",
      "2025-07-18 11:20:12,718 DEBUG Ensuring database directory exists: C:\\Users\\FilipeFurlanBellotti\\Desktop\n",
      "2025-07-18 11:20:12,722 INFO Database directory ensured: C:\\Users\\FilipeFurlanBellotti\\Desktop\n",
      "2025-07-18 11:20:12,722 DEBUG Attempting to create DuckDB at: C:\\Users\\FilipeFurlanBellotti\\Desktop\\clinisys_all.duckdb\n",
      "2025-07-18 11:20:12,746 INFO DuckDB database created or opened at: C:\\Users\\FilipeFurlanBellotti\\Desktop\\clinisys_all.duckdb\n",
      "2025-07-18 11:20:12,748 INFO DuckDB connection closed\n",
      "2025-07-18 11:20:12,748 INFO DuckDB database creation script finished successfully\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "os.chdir(\"g:/My Drive/projetos_individuais/Huntington\")\n",
    "!python clinisys/init_duckdb.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4a3e1f84",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-07-21 11:21:05,965 INFO Starting bronze loader\n",
      "2025-07-21 11:21:05,968 INFO DuckDB path: G:\\My Drive\\projetos_individuais\\Huntington\\database\\clinisys_all.duckdb\n",
      "2025-07-21 11:21:05,968 DEBUG Bronze loader started in debug mode\n",
      "2025-07-21 11:21:05,970 DEBUG Found 16 CSV files in g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\n",
      "2025-07-21 11:21:05,970 DEBUG Connecting to DuckDB at G:\\My Drive\\projetos_individuais\\Huntington\\database\\clinisys_all.duckdb\n",
      "2025-07-21 11:21:06,052 INFO Connected to DuckDB at G:\\My Drive\\projetos_individuais\\Huntington\\database\\clinisys_all.duckdb (file will be created if it does not exist)\n",
      "2025-07-21 11:21:06,053 DEBUG Connected to DuckDB at G:\\My Drive\\projetos_individuais\\Huntington\\database\\clinisys_all.duckdb (connection object: <duckdb.duckdb.DuckDBPyConnection object at 0x000002570717EF70>)\n",
      "2025-07-21 11:21:06,053 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicamentos.csv as table view_medicamentos ---\n",
      "2025-07-21 11:21:06,053 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicamentos.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,060 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicamentos.csv as table view_medicamentos ---\n",
      "2025-07-21 11:21:06,060 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicamentos_prescricoes.csv as table view_medicamentos_prescricoes ---\n",
      "2025-07-21 11:21:06,061 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicamentos_prescricoes.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,062 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicamentos_prescricoes.csv as table view_medicamentos_prescricoes ---\n",
      "2025-07-21 11:21:06,062 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicos.csv as table view_medicos ---\n",
      "2025-07-21 11:21:06,062 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicos.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,063 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_medicos.csv as table view_medicos ---\n",
      "2025-07-21 11:21:06,063 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_pacientes.csv as table view_pacientes ---\n",
      "2025-07-21 11:21:06,063 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_pacientes.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,063 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_pacientes.csv as table view_pacientes ---\n",
      "2025-07-21 11:21:06,064 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_tratamentos.csv as table view_tratamentos ---\n",
      "2025-07-21 11:21:06,064 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_tratamentos.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,064 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_tratamentos.csv as table view_tratamentos ---\n",
      "2025-07-21 11:21:06,065 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_unidades.csv as table view_unidades ---\n",
      "2025-07-21 11:21:06,065 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_unidades.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,065 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_unidades.csv as table view_unidades ---\n",
      "2025-07-21 11:21:06,066 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_congelamentos_embrioes.csv as table view_congelamentos_embrioes ---\n",
      "2025-07-21 11:21:06,066 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_congelamentos_embrioes.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,066 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_congelamentos_embrioes.csv as table view_congelamentos_embrioes ---\n",
      "2025-07-21 11:21:06,068 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_congelamentos_ovulos.csv as table view_congelamentos_ovulos ---\n",
      "2025-07-21 11:21:06,068 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_congelamentos_ovulos.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,068 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_congelamentos_ovulos.csv as table view_congelamentos_ovulos ---\n",
      "2025-07-21 11:21:06,068 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_descongelamentos_embrioes.csv as table view_descongelamentos_embrioes ---\n",
      "2025-07-21 11:21:06,068 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_descongelamentos_embrioes.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,069 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_descongelamentos_embrioes.csv as table view_descongelamentos_embrioes ---\n",
      "2025-07-21 11:21:06,069 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_descongelamentos_ovulos.csv as table view_descongelamentos_ovulos ---\n",
      "2025-07-21 11:21:06,070 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_descongelamentos_ovulos.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,070 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_descongelamentos_ovulos.csv as table view_descongelamentos_ovulos ---\n",
      "2025-07-21 11:21:06,070 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_embrioes_congelados.csv as table view_embrioes_congelados ---\n",
      "2025-07-21 11:21:06,070 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_embrioes_congelados.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,072 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_embrioes_congelados.csv as table view_embrioes_congelados ---\n",
      "2025-07-21 11:21:06,073 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_extrato_atendimentos_central.csv as table view_extrato_atendimentos_central ---\n",
      "2025-07-21 11:21:06,073 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_extrato_atendimentos_central.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,074 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_extrato_atendimentos_central.csv as table view_extrato_atendimentos_central ---\n",
      "2025-07-21 11:21:06,074 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_micromanipulacao.csv as table view_micromanipulacao ---\n",
      "2025-07-21 11:21:06,074 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_micromanipulacao.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,075 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_micromanipulacao.csv as table view_micromanipulacao ---\n",
      "2025-07-21 11:21:06,075 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_micromanipulacao_oocitos.csv as table view_micromanipulacao_oocitos ---\n",
      "2025-07-21 11:21:06,075 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_micromanipulacao_oocitos.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,076 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_micromanipulacao_oocitos.csv as table view_micromanipulacao_oocitos ---\n",
      "2025-07-21 11:21:06,076 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_orcamentos.csv as table view_orcamentos ---\n",
      "2025-07-21 11:21:06,076 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_orcamentos.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,077 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_orcamentos.csv as table view_orcamentos ---\n",
      "2025-07-21 11:21:06,077 DEBUG --- Start processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_procedimentos_financas.csv as table view_procedimentos_financas ---\n",
      "2025-07-21 11:21:06,077 ERROR Error loading g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_procedimentos_financas.csv: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "Traceback (most recent call last):\n",
      "  File \"g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\bronze_loader.py\", line 69, in main\n",
      "    df = pd.read_csv(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 1013, in read_csv\n",
      "    kwds_defaults = _refine_defaults_read(\n",
      "  File \"c:\\Users\\FilipeFurlanBellotti\\anaconda3\\envs\\try_request\\lib\\site-packages\\pandas\\io\\parsers\\readers.py\", line 2252, in _refine_defaults_read\n",
      "    raise ValueError(\n",
      "ValueError: on_bad_line can only be a callable function if engine='python' or 'pyarrow'\n",
      "2025-07-21 11:21:06,078 DEBUG --- Finished processing g:\\My Drive\\projetos_individuais\\Huntington\\clinisys\\data_output\\view_procedimentos_financas.csv as table view_procedimentos_financas ---\n",
      "2025-07-21 11:21:06,078 DEBUG Closed DuckDB connection\n",
      "2025-07-21 11:21:06,078 INFO Bronze loader finished successfully\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "\n",
    "# Make sure you are in the project root directory\n",
    "os.chdir(\"g:/My Drive/projetos_individuais/Huntington\")\n",
    "\n",
    "# Run the bronze loader script\n",
    "!python clinisys/bronze_loader.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dd7ea5e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Package             Version\n",
      "------------------- -----------\n",
      "asttokens           3.0.0\n",
      "Bottleneck          1.4.2\n",
      "certifi             2025.4.26\n",
      "charset-normalizer  3.4.2\n",
      "colorama            0.4.6\n",
      "comm                0.2.2\n",
      "contourpy           1.3.0\n",
      "cycler              0.12.1\n",
      "debugpy             1.8.14\n",
      "decorator           5.2.1\n",
      "duckdb              1.3.2\n",
      "exceptiongroup      1.3.0\n",
      "executing           2.2.0\n",
      "fonttools           4.58.5\n",
      "idna                3.10\n",
      "importlib_metadata  8.7.0\n",
      "importlib_resources 6.5.2\n",
      "ipykernel           6.29.5\n",
      "ipython             8.18.1\n",
      "jedi                0.19.2\n",
      "jupyter_client      8.6.3\n",
      "jupyter_core        5.8.1\n",
      "kiwisolver          1.4.7\n",
      "matplotlib          3.9.4\n",
      "matplotlib-inline   0.1.7\n",
      "mkl_fft             1.3.11\n",
      "mkl_random          1.2.8\n",
      "mkl-service         2.4.0\n",
      "nest_asyncio        1.6.0\n",
      "numexpr             2.10.1\n",
      "numpy               2.0.1\n",
      "packaging           25.0\n",
      "pandas              2.2.3\n",
      "parso               0.8.4\n",
      "pickleshare         0.7.5\n",
      "pillow              11.3.0\n",
      "pip                 25.1.1\n",
      "platformdirs        4.3.8\n",
      "prompt_toolkit      3.0.51\n",
      "psutil              7.0.0\n",
      "pure_eval           0.2.3\n",
      "Pygments            2.19.1\n",
      "pyparsing           3.2.3\n",
      "python-dateutil     2.9.0.post0\n",
      "pytz                2024.1\n",
      "pywin32             307\n",
      "PyYAML              6.0.2\n",
      "pyzmq               26.4.0\n",
      "requests            2.32.3\n",
      "seaborn             0.13.2\n",
      "setuptools          78.1.1\n",
      "six                 1.17.0\n",
      "stack_data          0.6.3\n",
      "tornado             6.5.1\n",
      "tqdm                4.67.1\n",
      "traitlets           5.14.3\n",
      "typing_extensions   4.13.2\n",
      "tzdata              2025.2\n",
      "urllib3             2.4.0\n",
      "wcwidth             0.2.13\n",
      "wheel               0.45.1\n",
      "zipp                3.22.0\n"
     ]
    }
   ],
   "source": [
    "!pip list"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "try_request",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.21"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
